services:
  db:
    image: postgres:16
    container_name: mystic_postgres
    environment:
      POSTGRES_USER: mystic
      POSTGRES_PASSWORD: mysticpass
      POSTGRES_DB: mystic
    ports:
      - "5432:5432"
    volumes:
      - mystic_pgdata:/var/lib/postgresql/data

volumes:
  mystic_pgdata:
