FLOW_PROMPTS: dict[str, str] = {
    "session_preview": "Generate a short preview with intrigue, specificity, and a soft deeper-layer teaser.",
    "session_reading": "Generate a full premium reading with a layered snapshot, a differentiated body, and a return invitation. For full/core readings, the structure should feel like: snapshot (core theme, main tension, best next move), then body (opening, astrological foundation, what your palm reveals when palm is present, what the cards are saying, where these signals agree, what this is asking of you, your next move, minimal return line). Astrology must visibly matter in combined/full readings: name the actual placements, chart tensions, elemental emphasis, or identity/need dynamics that are present, and explain what they reveal about the user and the question. Do not reduce astrology to setup flavor or let it disappear behind tarot. Palm must visibly matter when it is part of the flow: name the standout signals in human terms, explain what they suggest, and why they matter to the question. Tarot must be card-led, interpretive, and connected to the question: name the cards, explain what each individual card means for this person and this question, explain each card's role in the spread, then give a separate spread-level story that synthesises the cards into one coherent movement or tension. Do not let the tarot section collapse into a list of card names or a single generic paragraph. Make the expanded tarot state materially richer than the collapsed synthesis line, and keep summary and body distinct rather than paraphrasing the same point twice. When tarot is present, the tarot_message should feel premium and substantial: usually 3 paragraphs or roughly 180-260 words, with clear movement from card one, to card tension, to spread-level story. Avoid mechanical phrasing such as 'acts as the pattern' or 'functions as the role' unless absolutely necessary. Make the prose feel authored, not assembled.",
    "tarot_preview": "Generate a tarot preview that is clearly card-led, not a generic astrology teaser. Refer to the drawn card or cards when available, name symbolic meaning, and hint at how the spread or position changes the interpretation.",
    "tarot_reading": "Generate a full tarot reading that is unmistakably tarot-specific. Interpret the actual card or cards, explain their symbolism, reflect the spread or position logic when available, and synthesise the cards into a coherent reading with grounded guidance. The tarot narrative must do two distinct jobs: first, explain what each card means for this person in this question; second, explain the overall story the cards tell together. Make each section do a different job: opening sets the atmosphere, tarot narrative interprets the cards and spread, synthesis connects the pattern, and guidance gives concrete next steps. Do not repeat or paraphrase the same sentence across opening, narrative, synthesis, and guidance. Keep claims tied to the actual cards or spread, make guidance actionable rather than abstract, and avoid vague mystical boilerplate unless it is clearly earned by the cards. Avoid drifting into generic astrology or full-reading prose.",
    "daily_horoscope_preview": "Generate a true daily horoscope preview. Keep it clearly about today and make it fast to scan. The implied structure should be: today's headline, today's energy, best move, watch out for, plus a soft deeper-layer teaser.",
    "daily_horoscope_reading": "Generate a true full daily horoscope, not a generic astrology essay. Focus on today only. The implied structure should cover: today's theme, today's energy, best move, watch out for, people energy, work/focus, timing, and closing guidance.",
    "lunar_new_year_preview": "Generate a true Lunar New Year preview, not a daily horoscope, seasonal wellness note, or generic astrology reading. Frame it as the new year-cycle the user is entering. Use the lunar_context when present: anchor the preview in the user's birth zodiac, the current lunar year animal/element, and the interaction between them. Make the preview specific about the cycle theme, the symbolic character of the year, and one important opportunity or caution to carry into the year ahead.",
    "lunar_new_year_reading": "Generate a true full Lunar New Year reading with a recognisably year-ahead frame. Avoid generic season-ahead language, vague self-help, and recycled daily horoscope copy. This is not a daily reading. Use the lunar_context when present: the user's birth zodiac should matter, the current year animal and element should matter, and the interaction between them should shape the reading. The reading should clearly cover: the cycle theme of the Lunar New Year the person is entering, the year's symbolism and why it matters for them, likely luck/opportunity areas, likely caution/friction areas, what to welcome, what to release, and how to move through the year well with clear priorities. Make the guidance concrete and include multiple distinct carry-forward points rather than one generic paragraph. If the domain context includes reading_focus bullets, treat them as anchor rails and build around them rather than ignoring them.",
    "compatibility_preview": "Generate a chemistry-focused compatibility preview with clear relational tension and curiosity.",
    "compatibility_reading": "Generate a full compatibility reading with emotional dynamics, strengths, tensions, and grounded guidance.",
    "feng_shui_preview": "Generate a short Feng Shui preview focused on the most obvious energetic or practical shift in the space.",
    "feng_shui_analysis": "Generate a full Feng Shui analysis with grounded recommendations, prioritised next actions, and clear explanation.",
}
